[package]
name = "web_fs"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
cfg-if = { version = "1.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3", features = [] }